// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.2
// source: chat/chatpb/chat.proto

package chatpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ChatMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Room          string                 `protobuf:"bytes,1,opt,name=room,proto3" json:"room,omitempty"`
	From          string                 `protobuf:"bytes,2,opt,name=from,proto3" json:"from,omitempty"`
	Text          string                 `protobuf:"bytes,3,opt,name=text,proto3" json:"text,omitempty"`
	UnixMs        int64                  `protobuf:"varint,4,opt,name=unix_ms,json=unixMs,proto3" json:"unix_ms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChatMessage) Reset() {
	*x = ChatMessage{}
	mi := &file_chat_chatpb_chat_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChatMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatMessage) ProtoMessage() {}

func (x *ChatMessage) ProtoReflect() protoreflect.Message {
	mi := &file_chat_chatpb_chat_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatMessage.ProtoReflect.Descriptor instead.
func (*ChatMessage) Descriptor() ([]byte, []int) {
	return file_chat_chatpb_chat_proto_rawDescGZIP(), []int{0}
}

func (x *ChatMessage) GetRoom() string {
	if x != nil {
		return x.Room
	}
	return ""
}

func (x *ChatMessage) GetFrom() string {
	if x != nil {
		return x.From
	}
	return ""
}

func (x *ChatMessage) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *ChatMessage) GetUnixMs() int64 {
	if x != nil {
		return x.UnixMs
	}
	return 0
}

var File_chat_chatpb_chat_proto protoreflect.FileDescriptor

const file_chat_chatpb_chat_proto_rawDesc = "" +
	"\n" +
	"\x16chat/chatpb/chat.proto\x12\x04chat\"b\n" +
	"\vChatMessage\x12\x12\n" +
	"\x04room\x18\x01 \x01(\tR\x04room\x12\x12\n" +
	"\x04from\x18\x02 \x01(\tR\x04from\x12\x12\n" +
	"\x04text\x18\x03 \x01(\tR\x04text\x12\x17\n" +
	"\aunix_ms\x18\x04 \x01(\x03R\x06unixMs2?\n" +
	"\vChatService\x120\n" +
	"\x04Chat\x12\x11.chat.ChatMessage\x1a\x11.chat.ChatMessage(\x010\x01B'Z%example.com/chatty/chat/chatpb;chatpbb\x06proto3"

var (
	file_chat_chatpb_chat_proto_rawDescOnce sync.Once
	file_chat_chatpb_chat_proto_rawDescData []byte
)

func file_chat_chatpb_chat_proto_rawDescGZIP() []byte {
	file_chat_chatpb_chat_proto_rawDescOnce.Do(func() {
		file_chat_chatpb_chat_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_chat_chatpb_chat_proto_rawDesc), len(file_chat_chatpb_chat_proto_rawDesc)))
	})
	return file_chat_chatpb_chat_proto_rawDescData
}

var file_chat_chatpb_chat_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_chat_chatpb_chat_proto_goTypes = []any{
	(*ChatMessage)(nil), // 0: chat.ChatMessage
}
var file_chat_chatpb_chat_proto_depIdxs = []int32{
	0, // 0: chat.ChatService.Chat:input_type -> chat.ChatMessage
	0, // 1: chat.ChatService.Chat:output_type -> chat.ChatMessage
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_chat_chatpb_chat_proto_init() }
func file_chat_chatpb_chat_proto_init() {
	if File_chat_chatpb_chat_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_chat_chatpb_chat_proto_rawDesc), len(file_chat_chatpb_chat_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_chat_chatpb_chat_proto_goTypes,
		DependencyIndexes: file_chat_chatpb_chat_proto_depIdxs,
		MessageInfos:      file_chat_chatpb_chat_proto_msgTypes,
	}.Build()
	File_chat_chatpb_chat_proto = out.File
	file_chat_chatpb_chat_proto_goTypes = nil
	file_chat_chatpb_chat_proto_depIdxs = nil
}
